version: "3"

services:
  code-server:
    image: tnfssc/code-server:latest
    volumes:
      - ./workspace:/workspace

  cloudflared:
    image: cloudflare/cloudflared
    command: tunnel --no-autoupdate run --token <TOKEN>
